Task 1
blacklabel/kent-w-holt pull request #1
Opened 2023-08-31 10:46 UTC by Xillez

2023-09-01 15:06 UTC, mfilipiec requested changes
To sum up, I have no objections to the JavaScript code itself, it is clear. I only have a few suggestions and tips on how some things can be achieved using chart options. It is not necessary that you implement them because your solutions are also good, it's just good to know about them.

Just take another look at those ticks because one of the main goals of this quest was to figure out this.

2023-09-01 15:06 UTC, mfilipiec commented on highcharts-api/highcharts/1-simple-column/main.js
> +        endOnTick: false
> Try to figure out why sometimes yAxis.max isn't being taken into consideration and how to force Highcharts to set exactly the yAxis.max we want.

This can be a bit confusing at first, take a look at the `tickInterval` property: https://api.highcharts.com/highcharts/yAxis.tickInterval

2023-09-04 10:15 UTC, Xillez commented on highcharts-api/highcharts/1-simple-column/main.js
> +    });
So addPlotLine overwrites and not just appends lines?

2023-09-04 12:45 UTC, mfilipiec approved these changes
Good job! 🎉

2023-09-04 13:05 UTC, merged