highcharts-gantt/1-gantt-axes-groups
blacklabel/kent-w-holt pull request #15
Opened 2023-10-03 10:56 UTC by Xillez

2023-10-26 11:49 UTC, magdalena-gut requested changes

2023-10-26 11:49 UTC, magdalena-gut commented on highcharts-api/highcharts-gantt/1-gantt-axes-groups/main.js
>          data: [{
pointWidth seems to be not necessary here

2023-11-07 13:26 UTC, Xillez commented on highcharts-api/highcharts-gantt/1-gantt-axes-groups/main.js
>          data: [{
It was in the exercise already but I can remove it for sure :P

2023-11-07 14:02 UTC, magdalena-gut approved these changes
Perfect! Good job!

2023-11-07 14:02 UTC, magdalena-gut commented on highcharts-api/highcharts-gantt/1-gantt-axes-groups/main.js
>          data: [{
I haven't noticed that! My apologize!

2023-11-08 09:42 UTC, Xillez commented on highcharts-api/highcharts-gantt/1-gantt-axes-groups/main.js
>          data: [{
No worries

2023-11-08 09:43 UTC, merged