highcharts-maps/1-points-joinby
blacklabel/kent-w-holt pull request #18
Opened 2023-10-09 07:14 UTC by Xillez

2023-10-16 10:47 UTC, magdalena-gut requested changes
Just one last thing - the exercise requires adding a bubble series to the chart as well ;)

2023-10-16 10:47 UTC, magdalena-gut commented on highcharts-api/highcharts-maps/1-points-joinby/index.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.7.5/proj4.js"></script>
Since HC v10, it is no longer necessary as the projection is built-in

2023-10-16 10:47 UTC, magdalena-gut commented on highcharts-api/highcharts-maps/1-points-joinby/main.js
> +        keys: ['iso-a3', 'value'],
Great!

2023-10-16 11:44 UTC, Xillez commented
Ahh yeah true, forgot about that 😅 Will add soon 👍

2023-10-23 13:04 UTC, Xillez commented on highcharts-api/highcharts-maps/1-points-joinby/index.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.7.5/proj4.js"></script>
hmm, if I don't import it I get the "https://assets.highcharts.com/errors/21/" error and the series doesn't show though

2023-10-25 14:17 UTC, magdalena-gut requested changes
I noticed you were inspired by the GIF, but that wasn't precisely the goal of the exercise. The idea was to showcase the bubble series. No worries, though – I've added some comments based on your current code. Essentially, I've already provided the solution in the demos I sent, which I think better illustrates what I wanted to explain. 😉

2023-10-25 14:17 UTC, magdalena-gut commented on highcharts-api/highcharts-maps/1-points-joinby/main.js
> +        {
Instead of adding `allAreas: false` in the plotOptions and creating the background series, you can simply set allAreas: false for the second series, which covers the first one: https://jsfiddle.net/BlackLabel/r2z179fh/

2023-10-25 14:17 UTC, magdalena-gut commented on highcharts-api/highcharts-maps/1-points-joinby/index.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.7.5/proj4.js"></script>
Just to clear things up about what I mentioned earlier: yes, you'd need proj4 when using lat/lon, but if you don't use the coordinating system, it's not needed. I hope the following demos will illustrate more clearly what I wanted to explain:
 
- Example 1: [Mapbubble Data Shown by iso-a3 + JS Map](https://jsfiddle.net/BlackLabel/15j2xhg8/) (Proj4 not necessary here)
- Example 2: [Mapbubble Data Shown by Lat/Lon + JS Map + Proj4](https://jsfiddle.net/BlackLabel/6wejkgdt/) (Proj4 necessary here due to lon/lat)
- Example 3: [Mapbubble Data Shown by Lat/Lon + TopoJSON Used](https://jsfiddle.net/BlackLabel/phm68v2L/) (Proj4 not necessary here due to TopoJSON used)

Also, I recommend you to read this great post on our blog: [Highcharts Now Prefers TopoJSON Maps](https://www.highcharts.com/blog/tutorials/highcharts-now-prefers-topojson-maps/)

2023-11-07 11:25 UTC, magdalena-gut approved these changes

2023-11-07 13:28 UTC, merged