task2
blacklabel/kent-w-holt pull request #2
Opened 2023-08-31 11:36 UTC by Xillez

2023-09-01 15:10 UTC, magdalena-gut commented on highcharts-api/highcharts/1-simple-column/main.js
> +    chart.yAxis[0].addPlotLine({
You've only used one way to draw the lines. Try finding two more ways to do achieve that. Let me know if you will need any tips!

2023-09-04 19:14 UTC, Xillez commented on highcharts-api/highcharts/1-simple-column/main.js
> +    chart.yAxis[0].addPlotLine({
Tried to add all methods I could find although I'm a little uncertain if the removePlotLine+addPlotLine for the maximum indicator actually count as one 😅 

I tried to add it through the yAxis config but didn't really see a clear and neat way of updating them, and given update() overwrites them, I have to also re-add it afterwards, which isn't really all that pretty 😅

2023-09-05 09:01 UTC, magdalena-gut commented on highcharts-api/highcharts/1-simple-column/main.js
> +    chart.yAxis[0].addPlotLine({
Yes, in practice, that solution might not make much sense 😅 However, we can consider it one of the solutions as you practised load event and update method  🙌 
You were mainly focused on adding plot lines in this task, but it's possible to add lines (circles) not only through plotLines but also by adding a new series or using the SVGRenderer. The latter approach is quite important in Highcharts, so I'd like you to practice it a bit. Could you please create a responsive circle on the chart using the SVG renderer? You can refer to the Highcharts.SVGRenderer documentation here: https://api.highcharts.com/class-reference/Highcharts.SVGRenderer"

2023-09-05 10:03 UTC, Xillez commented on highcharts-api/highcharts/1-simple-column/main.js
> +    chart.yAxis[0].addPlotLine({
Aha I see, will do! 👍

2023-09-06 18:55 UTC, magdalena-gut requested changes
Great, nice way of positioning the circle relative to the chart.  Just one more nitpick here. When we resize the chart, the circle is moving. The `load `event allows to manipulation of the chart only once, when the chart is finished loading.  Try to use chart `render `event (Fires after the initial load of the chart and after each redraw) and make the circle responsive (The r should resize with resizing chart. You will face the multiplication of the circles each time when resizing, which you can resolve different ways).
Quick overview of the API:
https://api.highcharts.com/highcharts/chart.events.load
https://api.highcharts.com/highcharts/chart.events.redraw - just FYI
https://api.highcharts.com/highcharts/chart.events.render
The nice demo that shows the differences between these three:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/events-render/

2023-09-07 16:57 UTC, magdalena-gut approved these changes
Nicely done, good job!💪

2023-09-07 16:57 UTC, magdalena-gut commented on highcharts-api/highcharts/2-polar-rings/main.js
> +            render: function () {
JFYI, another approach could be prioritize encapsulation and isolation when rendering the circle:
```
    events: {
      render: function() {
        const chart = this,
          yAxis = this.yAxis[0],
          max = yAxis.dataMax,
          cx = chart.plotLeft + chart.pane[0].center[0],
          cy = chart.plotTop + chart.pane[0].center[1];
        if (!chart.circle) {
          chart.circle = chart.renderer.circle().attr({
            fill: 'none',
            stroke: '#43BDFF6C',
            'stroke-width': 1,
            'stroke-dasharray': '5,5'
          }).add();
        }
        chart.circle.attr({
          cx: cx,
          cy: cy,
          r: yAxis.len * (max / yAxis.max),
        });
      }
    }
```

2023-09-08 07:37 UTC, Xillez commented on highcharts-api/highcharts/2-polar-rings/main.js
> +            render: function () {
True, thanks for the tip 👍

2023-09-08 07:37 UTC, merged