highcharts/9-3d-charts
blacklabel/kent-w-holt pull request #8
Opened 2023-09-15 06:41 UTC by Xillez

2023-09-18 12:42 UTC, mfilipiec requested changes
A very nice solution, I have no objections except that instead of a uniform color for the points, you could try setting a gradient as in the GIF.

As an interesting fact. There is a module that can achieve a similar effect: https://blacklabel.github.io/projections/

2023-09-18 12:42 UTC, mfilipiec commented on highcharts-api/highcharts/9-3d-charts/part1.js
> +            ],
It would be nice if, instead of a solid color for the points, you could try setting a gradient as in the GIF

2023-09-19 07:22 UTC, Xillez commented on highcharts-api/highcharts/9-3d-charts/part1.js
> +            ],
I also see that the markers are oriented to the normal of the axis plane it's projected on but not really sure how to do that 🤔

2023-09-19 10:42 UTC, mfilipiec approved these changes
Nice! 🎉

2023-09-19 10:51 UTC, mfilipiec commented on highcharts-api/highcharts/9-3d-charts/part1.js
> +            ],
You're right, I didn't notice that. From what I remember, that's probably why it was better to use a module, but you can skip it for now and focus on other tasks, if you want, you can come back to it after doing the rest 😉

2023-09-19 11:21 UTC, merged