highcharts/10-histogram-point-select
blacklabel/kent-w-holt pull request #9
Opened 2023-09-18 13:33 UTC by Xillez

2023-09-20 09:42 UTC, jakubjanuchta requested changes
Everything looks good, just one small change requested.

2023-09-20 09:42 UTC, jakubjanuchta commented on highcharts-api/highcharts/10-histogram-point-select/main.js
> +        {},
The y position of the scatter points differ regarding to the histogram bins looks different on the gif, please check that out.

2023-09-20 09:42 UTC, jakubjanuchta commented on highcharts-api/highcharts/10-histogram-point-select/main.js
> +                        for (const point of this.series.baseSeries.points) {
Just FIY, `for of` loop is the slowest of all loops. In this case, it doesn't really matter, but when it comes to deal with big data, it could be problematic. Here you can read something about it: [Article](https://dev.to/siddiqus/which-for-loop-is-the-fastest-in-javascript-4hdf)

2023-09-20 10:59 UTC, Xillez commented on highcharts-api/highcharts/10-histogram-point-select/main.js
> +                        for (const point of this.series.baseSeries.points) {
That is really useful 👍 thanks for the tip!

2023-09-21 06:58 UTC, jakubjanuchta approved these changes
LGTM, thanks!

2023-09-26 10:00 UTC, merged